Repository wonjin-dev/gamble, pull requests merged in 2023-01, with the labels that each got.

#3 :recycle: 스크립트 수정
  .husky/pre-commit
  README.md
  cypress.config.ts
  package-lock.json
  package.json
Labels: refactor

#6 :sparkles: BaseButton 컴포넌트 작성
  .husky/pre-commit
  .storybook/main.js
  README.md
  jest.config.js
  package-lock.json
  package.json
  pages/index.tsx
  src/@views/@common/BaseButton.tsx
  src/@views/Gamble/index.tsx
  src/@views/index.tsx
  src/__test__/rem.test.ts
  src/__test__/sample
  src/stories/BaseButton.stories.tsx
  src/stories/sample
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
  tsconfig.json
Labels: feat

#12 :sparkles: 결과 컴포넌트 작성
  jest.config.js
  public/img/BEAUTY.png
  public/img/CHEETAH.png
  public/img/CHIMP.png
  public/img/GOLDFISH.png
  public/img/INTELLIGENCE.png
  public/img/PROBOSIC_MONKEY.png
  public/img/SLOTH.png
  public/img/SNAIL.png
  public/img/SPEED.png
  public/img/STRENGTH.png
  public/img/TIGER.png
  public/img/WOLF.png
  src/@views/Gamble/components/Result.tsx
  src/@views/Gamble/hooks/useGamble.ts
  src/@views/Gamble/index.tsx
  src/constants/image.ts
  tsconfig.json
Labels: feat, style

#13 🎨 강화 섹션 컴포넌트 작성
  .gitignore
  package-lock.json
  src/@views/Gamble/components/GambleSection.tsx
  src/@views/Gamble/components/Section/Enchant.tsx
  src/@views/Gamble/components/Section/Score.tsx
  src/@views/Gamble/index.tsx
Labels: feat, style

#27 :art: gamble 페이지 마크업
  README.md
  src/@views/Gamble/components/Board.tsx
  src/@views/Gamble/components/Result.tsx
  src/@views/Gamble/components/Section/Score.tsx
  src/@views/Gamble/components/Section/index.tsx
  src/hooks/gamble/useGambleResult.ts
Labels: style

#28 ✅ gamble E2E 작성
  .husky/pre-commit
  cypress/e2e/ e2e.cy.ts
  cypress/e2e/gamble.cy.ts
Labels: test

#34 ✅ 능력 요소 랜덤 생성함수 테스트 코드 작성
  src/__test__/generator.test.ts
  src/utils/generators.ts
Labels: test

#38 ✨ 결과 창이 노출되기 전에 0.8초간 스피닝 스크린이 노출됩니다
  public/img/spinner.svg
  src/@views/@common/BaseButton.tsx
  src/@views/@common/Spinner.tsx
  src/@views/Gamble/components/Board.tsx
  src/@views/Gamble/components/Result.tsx
  src/@views/Gamble/index.tsx
  src/__test__/generator.test.ts
  src/constants/image.ts
  src/hooks/gamble/useGamble.ts
  src/hooks/gamble/useProbability.ts
  src/stories/Spinner.stories.tsx
  src/styles/keyframe.ts
  src/utils/generators.ts
Labels: feat, style

#41 🐛 typescript cypress 타입 에러로 인한 빌드 실패 수정
  tsconfig.json
Labels: bug

#43 :bug: 강화를 10번 한 이후에도 강화 버튼 클릭 시 강화 확률이 변경됩니다
  src/hooks/gamble/useGamble.ts
Labels: bug

#44 :sparkles: 페이지 레이아웃 구현
  pages/_app.tsx
  pages/index.tsx
  src/@views/@common/Layout/index.tsx
Labels: feat

#48 :recycle: 코드 리팩터링
  src/@views/Gamble/components/Section/index.tsx
  src/@views/Gamble/index.tsx
  src/__test__/gamble.test.ts
  src/__test__/generator.test.ts
  src/hooks/gamble/useGamble.ts
  src/hooks/gamble/useGambleResult.ts
  src/hooks/gamble/useProbability.ts
  src/utils/generators.ts
Labels: refactor

#52 🐛 결과 배경 음악 무한 재생되는 오류 수정
  src/@views/Gamble/components/Result.tsx
  src/@views/Gamble/index.tsx
  src/hooks/useSound.ts
Labels: bug

#50 :art: 마크업 예쁘게 변경하기
  .eslintrc.json
  cypress/e2e/gamble.cy.ts
  pages/_document.tsx
  src/@views/@common/Layout/index.tsx
  src/@views/@common/Modals/BaseModal.tsx
  src/@views/@common/Modals/ConfirmModal.tsx
  src/@views/@common/Modals/TextToast.tsx
  src/@views/Gamble/components/GambleResetModalContent.tsx
  src/@views/Gamble/components/Result.tsx
  src/@views/Gamble/components/Section/index.tsx
  src/@views/Gamble/index.tsx
  src/constants/key.ts
  src/hooks/useModal.ts
  src/hooks/useScrollLock.ts
  src/hooks/useSound.ts
  src/hooks/useToast.ts
  src/store/toast.ts
  src/styles/GlobalStyle.tsx
  src/styles/keyframe.ts
  src/styles/theme.ts
Labels: feat, refactor, style, WIP

#56 🎨 전역 페이지 레이아웃 퍼블리싱
  README.md
  src/@views/@common/Layout/index.tsx
  src/@views/@common/Modals/ConfirmModal.tsx
  src/@views/Gamble/components/Board.tsx
  src/@views/Gamble/components/GambleResetModalContent.tsx
  src/@views/Gamble/components/Section/Score.tsx
  src/@views/Gamble/components/Section/index.tsx
  src/@views/Gamble/index.tsx
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
Labels: style
